export const stakingVaultAbi = [
    {
        type: 'function',
        stateMutability: 'view',
        name: 'stakingToken',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'rewardToken',
        inputs: [],
        outputs: [{ name: '', type: 'address' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'totalStaked',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'rewardRate',
        inputs: [],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'balanceOf',
        inputs: [{ name: 'account', type: 'address' }],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'earned',
        inputs: [{ name: 'account', type: 'address' }],
        outputs: [{ name: '', type: 'uint256' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'paused',
        inputs: [],
        outputs: [{ name: '', type: 'bool' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'DEFAULT_ADMIN_ROLE',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'PAUSER_ROLE',
        inputs: [],
        outputs: [{ name: '', type: 'bytes32' }],
    },
    {
        type: 'function',
        stateMutability: 'view',
        name: 'hasRole',
        inputs: [
            { name: 'role', type: 'bytes32' },
            { name: 'account', type: 'address' },
        ],
        outputs: [{ name: '', type: 'bool' }],
    },
    {
        type: 'function',
        stateMutability: 'nonpayable',
        name: 'stake',
        inputs: [{ name: 'amount', type: 'uint256' }],
        outputs: [],
    },
    {
        type: 'function',
        stateMutability: 'nonpayable',
        name: 'withdraw',
        inputs: [{ name: 'amount', type: 'uint256' }],
        outputs: [],
    },
    {
        type: 'function',
        stateMutability: 'nonpayable',
        name: 'claimRewards',
        inputs: [],
        outputs: [],
    },
    {
        type: 'function',
        stateMutability: 'nonpayable',
        name: 'setRewardRate',
        inputs: [{ name: 'newRewardRate', type: 'uint256' }],
        outputs: [],
    },
    {
        type: 'function',
        stateMutability: 'nonpayable',
        name: 'pause',
        inputs: [],
        outputs: [],
    },
    {
        type: 'function',
        stateMutability: 'nonpayable',
        name: 'unpause',
        inputs: [],
        outputs: [],
    },
] as const