const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000' as const

export const STAKE_TOKEN_ADDRESS =
    (process.env.NEXT_PUBLIC_STAKE_TOKEN_ADDRESS || ZERO_ADDRESS) as `0x${string}`

export const REWARD_TOKEN_ADDRESS =
    (process.env.NEXT_PUBLIC_REWARD_TOKEN_ADDRESS || ZERO_ADDRESS) as `0x${string}`

export const VAULT_ADDRESS =
    (process.env.NEXT_PUBLIC_VAULT_ADDRESS || ZERO_ADDRESS) as `0x${string}`

export const HAS_CONTRACT_ENV =
    STAKE_TOKEN_ADDRESS !== ZERO_ADDRESS &&
    REWARD_TOKEN_ADDRESS !== ZERO_ADDRESS &&
    VAULT_ADDRESS !== ZERO_ADDRESS
